CRM_NAME :=

CRM_SRC :=
CRM_INCS :=
CRM_IMPORT_INCLUDES_FROM_SHARED_LIBRARIES_HOST_ONLY :=
CRM_REQUIRED_MODULES :=
CRM_CFLAGS :=

CRM_SHARED_LIBS_ANDROID_ONLY :=
CRM_SHARED_LIBS_HOST_ONLY :=
CRM_SHARED_LIBS :=

CRM_STATIC_LIBS_HOST_ONLY :=
CRM_STATIC_LIBS :=

CRM_TARGET :=
CRM_DISABLE_HOST_TARGET :=
CRM_DISABLE_ANDROID_TARGET :=

CRM_LANG :=

CRM_XML_FOLDER :=
CRM_XML_MODULE := "crm"

CRM_COPY_HEADERS :=
CRM_COPY_HEADERS_TO :=

include $(CLEAR_VARS)
